[package]
name = "pakhi"
version = "0.9.0"
authors = ["Shafin Ashraf"]
edition = "2018"

[dev-dependencies]
lazy_static = "1.4.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html