[package]
name = "pakhi"
version = "0.0.4"
authors = ["Shafin Ashraf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
#debug = true